### ISSUE TITLE
Just some annotations...

### ISSUE THREAD

**Issue by R-J** [hazulu/superb-login#1]
I would suggest you either rename the repo to SuperbLogin or add it to the README that the folder must be renamed like that. Otherwise the plugin couldn't be disabled.

Conventions are to name the class Something_Plugin_ so you should use "class SuperbLogin_Plugin_ extends...". Another convention is to save *.js files in a subfolder called "js" and *.css files in a subfolder called "design".

There is already a jquery-ui file shipped with Vanilla which you should use instead of loading another copy of jquery-ui. Simply ensure that it is loaded by using `$Sender->AddJsFile('jquery-ui-1.8.17.custom.min.js');` in your plugin.

You have registered a permission without actually using it. No need for that ;-)

All your scripts are added even if the user is not signed in. Just to the UserID check you have done in other places also before adding those files.

Instead of adding div#exposeMask with every page load, I would add it via JavaScript (which you need to display your login box nevertheless) only when the sign in button is pressed.

You add a lot of markup after that line: `if ($AssetName == "Head"){` and then you include a view. Why not put **all** the html in the view?

After clicking the sign in button, the window is not scrolled to top. I think you should add that for convenience - and talking of convenience: why not already put focus on username if you are already using JS?

I've tested the script but because I wanted to test, I hit "Sign In" but didn't want to sign in. So I had to close that form but there is no close button... :-(

Styling doesn't work for me, although I think I'm using an unaltered version of +Baseline

**Comment by hazulu** [comment]
Thank you! I've added some of the enhancements you suggested, and plan on adding more soon.

You have to click on the white overlay of the website to exit the login panel. I'm also not sure why styling doesn't work for you... I'll have to look into that.
